// ############################
// Generated by Mooncake
// Date: 2022-08-29 16:14:06
// Source: tipos/interface1/interface1.go
// ############################
package mocks

import (
	"reflect"
	"github.com/GuilhermeCaruso/mooncake"
)
type MockImprimivel struct {
	agent              *mooncake.MooncakeAgent
	internalController *InternalMockImprimivel
}

func NewMockImprimivel(agent *mooncake.MooncakeAgent) *MockImprimivel {
	internal := new(MockImprimivel)
	internal.agent = agent
	internal.internalController = &InternalMockImprimivel{
		mock: internal,
	}
	return internal
}

func(m *MockImprimivel) ToString() (result0 string) {
	method := "ToString"

	result := m.agent.GetCall(method)

	result0,_ = result[0].Value.(string)

	return
}


func (immi *MockImprimivel) Prepare() *InternalMockImprimivel {
	return immi.internalController
}

type InternalMockImprimivel struct {
	mock *MockImprimivel
}


func (im *InternalMockImprimivel) ToString() *mooncake.AgentController {
	method := "ToString"
	methodType := reflect.TypeOf((*MockImprimivel)(nil).ToString)

	return im.mock.agent.SetCall(method, methodType)
}

